export const LANGUAGES_OPTIONS = [
  { code: 'am-ET', name: 'amharic' },
  { code: 'ar-SA', name: 'arabic' },
  { code: 'be-BY', name: 'bielarus' },
  { code: 'bem-ZM', name: 'bemba' },
  { code: 'bi-VU', name: 'bislama' },
  { code: 'bjs-BB', name: 'bajan' },
  { code: 'bn-IN', name: 'bengali' },
  { code: 'bo-CN', name: 'tibetan' },
  { code: 'br-FR', name: 'breton' },
  { code: 'bs-BA', name: 'bosnian' },
  { code: 'ca-ES', name: 'catalan' },
  { code: 'cop-EG', name: 'coptic' },
  { code: 'cs-CZ', name: 'czech' },
  { code: 'cy-GB', name: 'welsh' },
  { code: 'da-DK', name: 'danish' },
  { code: 'dz-BT', name: 'dzongkha' },
  { code: 'de-DE', name: 'german' },
  { code: 'dv-MV', name: 'maldivian' },
  { code: 'el-GR', name: 'greek' },
  { code: 'en-GB', name: 'english' },
  { code: 'es-ES', name: 'spanish' },
  { code: 'et-EE', name: 'estonian' },
  { code: 'eu-ES', name: 'basque' },
  { code: 'fa-IR', name: 'persian' },
  { code: 'fi-FI', name: 'finnish' },
  { code: 'fn-FNG', name: 'fanagalo' },
  { code: 'fo-FO', name: 'faroese' },
  { code: 'fr-FR', name: 'french' },
  { code: 'gl-ES', name: 'galician' },
  { code: 'gu-IN', name: 'gujarati' },
  { code: 'ha-NE', name: 'hausa' },
  { code: 'he-IL', name: 'hebrew' },
  { code: 'hi-IN', name: 'hindi' },
  { code: 'hr-HR', name: 'croatian' },
  { code: 'hu-HU', name: 'hungarian' },
  { code: 'id-ID', name: 'indonesian' },
  { code: 'is-IS', name: 'icelandic' },
  { code: 'it-IT', name: 'italian' },
  { code: 'ja-JP', name: 'japanese' },
  { code: 'kk-KZ', name: 'kazakh' },
  { code: 'km-KM', name: 'khmer' },
  { code: 'kn-IN', name: 'kannada' },
  { code: 'ko-KR', name: 'korean' },
  { code: 'ku-TR', name: 'kurdish' },
  { code: 'ky-KG', name: 'kyrgyz' },
  { code: 'la-VA', name: 'latin' },
  { code: 'lo-LA', name: 'lao' },
  { code: 'lv-LV', name: 'latvian' },
  { code: 'men-SL', name: 'mende' },
  { code: 'mg-MG', name: 'malagasy' },
  { code: 'mi-NZ', name: 'maori' },
  { code: 'ms-MY', name: 'malay' },
  { code: 'mt-MT', name: 'maltese' },
  { code: 'my-MM', name: 'burmese' },
  { code: 'ne-NP', name: 'nepali' },
  { code: 'niu-NU', name: 'niuean' },
  { code: 'nl-NL', name: 'dutch' },
  { code: 'no-NO', name: 'norwegian' },
  { code: 'ny-MW', name: 'nyanja' },
  { code: 'ur-PK', name: 'pakistani' },
  { code: 'pau-PW', name: 'palauan' },
  { code: 'pa-IN', name: 'panjabi' },
  { code: 'ps-PK', name: 'pashto' },
  { code: 'pis-SB', name: 'pijin' },
  { code: 'pl-PL', name: 'polish' },
  { code: 'pt-PT', name: 'portuguese' },
  { code: 'rn-BI', name: 'kirundi' },
  { code: 'ro-RO', name: 'romanian' },
  { code: 'ru-RU', name: 'russian' },
  { code: 'sg-CF', name: 'sango' },
  { code: 'si-LK', name: 'sinhala' },
  { code: 'sk-SK', name: 'slovak' },
  { code: 'sm-WS', name: 'samoan' },
  { code: 'sn-ZW', name: 'shona' },
  { code: 'so-SO', name: 'somali' },
  { code: 'sq-AL', name: 'albanian' },
  { code: 'sr-RS', name: 'serbian' },
  { code: 'sv-SE', name: 'swedish' },
  { code: 'sw-SZ', name: 'swahili' },
  { code: 'ta-LK', name: 'tamil' },
  { code: 'te-IN', name: 'telugu' },
  { code: 'tet-TL', name: 'tetum' },
  { code: 'tg-TJ', name: 'tajik' },
  { code: 'th-TH', name: 'thai' },
  { code: 'ti-TI', name: 'tigrinya' },
  { code: 'tk-TM', name: 'turkmen' },
  { code: 'tl-PH', name: 'tagalog' },
  { code: 'tn-BW', name: 'tswana' },
  { code: 'to-TO', name: 'tongan' },
  { code: 'tr-TR', name: 'turkish' },
  { code: 'uk-UA', name: 'ukrainian' },
  { code: 'uz-UZ', name: 'uzbek' },
  { code: 'vi-VN', name: 'vietnamese' },
  { code: 'wo-SN', name: 'wolof' },
  { code: 'xh-ZA', name: 'xhosa' },
  { code: 'yi-YD', name: 'yiddish' },
  { code: 'zu-ZA', name: 'zulu' },
];

// export const LANGUAGES_OPTION = {
//   'am-ET': 'Amharic',
//   'ar-SA': 'Arabic',
//   'be-BY': 'Bielarus',
//   'bem-ZM': 'Bemba',
//   'bi-VU': 'Bislama',
//   'bjs-BB': 'Bajan',
//   'bn-IN': 'Bengali',
//   'bo-CN': 'Tibetan',
//   'br-FR': 'Breton',
//   'bs-BA': 'Bosnian',
//   'ca-ES': 'Catalan',
//   'cop-EG': 'Coptic',
//   'cs-CZ': 'Czech',
//   'cy-GB': 'Welsh',
//   'da-DK': 'Danish',
//   'dz-BT': 'Dzongkha',
//   'de-DE': 'German',
//   'dv-MV': 'Maldivian',
//   'el-GR': 'Greek',
//   'en-GB': 'English',
//   'es-ES': 'Spanish',
//   'et-EE': 'Estonian',
//   'eu-ES': 'Basque',
//   'fa-IR': 'Persian',
//   'fi-FI': 'Finnish',
//   'fn-FNG': 'Fanagalo',
//   'fo-FO': 'Faroese',
//   'fr-FR': 'French',
//   'gl-ES': 'Galician',
//   'gu-IN': 'Gujarati',
//   'ha-NE': 'Hausa',
//   'he-IL': 'Hebrew',
//   'hi-IN': 'Hindi',
//   'hr-HR': 'Croatian',
//   'hu-HU': 'Hungarian',
//   'id-ID': 'Indonesian',
//   'is-IS': 'Icelandic',
//   'it-IT': 'Italian',
//   'ja-JP': 'Japanese',
//   'kk-KZ': 'Kazakh',
//   'km-KM': 'Khmer',
//   'kn-IN': 'Kannada',
//   'ko-KR': 'Korean',
//   'ku-TR': 'Kurdish',
//   'ky-KG': 'Kyrgyz',
//   'la-VA': 'Latin',
//   'lo-LA': 'Lao',
//   'lv-LV': 'Latvian',
//   'men-SL': 'Mende',
//   'mg-MG': 'Malagasy',
//   'mi-NZ': 'Maori',
//   'ms-MY': 'Malay',
//   'mt-MT': 'Maltese',
//   'my-MM': 'Burmese',
//   'ne-NP': 'Nepali',
//   'niu-NU': 'Niuean',
//   'nl-NL': 'Dutch',
//   'no-NO': 'Norwegian',
//   'ny-MW': 'Nyanja',
//   'ur-PK': 'Pakistani',
//   'pau-PW': 'Palauan',
//   'pa-IN': 'Panjabi',
//   'ps-PK': 'Pashto',
//   'pis-SB': 'Pijin',
//   'pl-PL': 'Polish',
//   'pt-PT': 'Portuguese',
//   'rn-BI': 'Kirundi',
//   'ro-RO': 'Romanian',
//   'ru-RU': 'Russian',
//   'sg-CF': 'Sango',
//   'si-LK': 'Sinhala',
//   'sk-SK': 'Slovak',
//   'sm-WS': 'Samoan',
//   'sn-ZW': 'Shona',
//   'so-SO': 'Somali',
//   'sq-AL': 'Albanian',
//   'sr-RS': 'Serbian',
//   'sv-SE': 'Swedish',
//   'sw-SZ': 'Swahili',
//   'ta-LK': 'Tamil',
//   'te-IN': 'Telugu',
//   'tet-TL': 'Tetum',
//   'tg-TJ': 'Tajik',
//   'th-TH': 'Thai',
//   'ti-TI': 'Tigrinya',
//   'tk-TM': 'Turkmen',
//   'tl-PH': 'Tagalog',
//   'tn-BW': 'Tswana',
//   'to-TO': 'Tongan',
//   'tr-TR': 'Turkish',
//   'uk-UA': 'Ukrainian',
//   'uz-UZ': 'Uzbek',
//   'vi-VN': 'Vietnamese',
//   'wo-SN': 'Wolof',
//   'xh-ZA': 'Xhosa',
//   'yi-YD': 'Yiddish',
//   'zu-ZA': 'Zulu',
// };
